name: Metrics
on:
  schedule:
    - cron: "0 */8 * * *" # Update every 8 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push the resulting SVG
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} 

          config_display: minimal 
          config_octicon: no

          # Calendar plugin (You might need to adjust your token name, GITHUB_TOKEN is recommended for profile repos)
          plugin_calendar: yes
          plugin_calendar_limit: 0
