name: Tic Tac Toe

on:
  issues:
    types: [opened]

jobs:
  move:
    permissions:
      issues: write
      contents: write
    runs-on: ubuntu-latest
    # Only run if the issue title starts with 'ttb|'
    if: startsWith(github.event.issue.title, 'ttb|')

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Play Tic Tac Toe
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # If you have no dependencies, you can skip pip install
          python src/tictactoe.py

      - name: Commit and push changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${ISSUE_TITLE} by ${ISSUE_AUTHOR}"
          git push
