name: Tic Tac Toe
on:
  issues:
    types: [opened]

jobs:
  play:
    if: startsWith(github.event.issue.title, 'ttb|')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - setup-python: 
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Logic
        run: python src/tictactoe.py
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Move played via issue" || exit 0
          git push
      - name: Close Issue
        run: gh issue close ${{ github.event.issue.number }} --comment "Move recorded!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
